Initial creation of API
SynergiTech/creditsafe-connect pull request #1
Opened 2018-12-10 12:52 UTC by seanlanepgh

2018-12-10 13:21 UTC, williamrenfrew requested changes

2018-12-10 13:21 UTC, williamrenfrew commented on src/Client.php
> +     *  to the api and is only valid for a hour
'an hour'

2018-12-10 13:21 UTC, williamrenfrew commented on src/Client.php
> +     * @param  string $type     Stores the type of HTTP Request e.g GET ,POST
'Sets'

2018-12-10 13:21 UTC, williamrenfrew commented on src/Client.php
> +     *  A function that handles the creation of GET  Request
A function that handles the creation of a GET Request

2018-12-10 13:21 UTC, williamrenfrew commented on src/Client.php
> +     * @param  string $endpoint  A endpoint used to create a request
An

2018-12-10 13:21 UTC, williamrenfrew commented on src/ListResult.php
> +     * This constructor is used to build the ListResult
Descriptors reqd

2018-12-10 13:38 UTC, williamrenfrew requested changes
Some general formatting required too

2018-12-10 13:38 UTC, williamrenfrew commented on src/Client.php
> +            $guzzleArgs ['query']= $params ;
```suggestion
            $guzzleArgs ['query'] = $params;
```

2018-12-10 13:38 UTC, williamrenfrew commented on src/Client.php
> +            $guzzleArgs['json']= $params ;
```suggestion
            $guzzleArgs['json'] = $params;
```

2018-12-10 13:42 UTC, willpower232 requested changes
great start, please have another look through all the files and make sure you're being consistent, particularly with white space usage. Hopefully atom can sort out most of it but do have another look after too.

2018-12-10 13:42 UTC, willpower232 commented on src/ListResult.php
> +     * @param Client $client      [description]
complete descriptions or remove `[description]`

2018-12-10 13:42 UTC, willpower232 commented on src/ListResult.php
> +    public function current()
probably not return void?

2018-12-10 13:42 UTC, willpower232 commented on src/Client.php
> +    public function __construct($config = [])
missing type declaration

2018-12-10 13:42 UTC, willpower232 commented on src/ListResult.php
> +    public function page(int $num)
missing return type declaration

2018-12-10 13:42 UTC, willpower232 commented on src/ListResult.php
> +    public function next()
missing return type declaration

2018-12-10 13:42 UTC, willpower232 commented on src/ListResult.php
> +    public function key()
missing return type declaration

2018-12-10 13:42 UTC, willpower232 commented on src/ListResult.php
> +    public function valid()
missing return type declaration

2018-12-10 13:42 UTC, willpower232 commented on src/Models/CompanySearchResult.php
> +    public function get()
missing return type declaration

2018-12-10 13:42 UTC, willpower232 commented on tests/ClientTest.php
> +    public function testAuthorizationSuccess($guzzle)
missing function and return type declarations

2018-12-10 16:28 UTC, Josh-G requested changes
a couple of blockers

2018-12-10 16:28 UTC, Josh-G commented on README.md
> +$creditsafe->companies()->searchCriteria(['countries'=>'GB']);
```suggestion
$creditsafe->companies()->searchCriteria(['countries' => 'GB']);
```

2018-12-10 16:28 UTC, Josh-G commented on README.md
> +$search = $creditsafe->companies()->search(['countries'=>'GB', 'name' => 'GOOGLE UK LIMITED']);
```suggestion
$search = $creditsafe->companies()->search(['countries' => 'GB', 'name' => 'GOOGLE UK LIMITED']);
```

2018-12-10 16:28 UTC, Josh-G commented on src/ListResult.php
> +     * @return self   Returns PageSize
```suggestion
     * @return self
```
wrong description, probably doesn't need one

2018-12-10 16:28 UTC, Josh-G commented on src/ListResult.php
> +    private function getParams(): array
```suggestion
    private function getParams() : array
```

2018-12-10 16:28 UTC, Josh-G commented on src/Models/Company.php
> +    /**
```suggestion

    /**
```

2018-12-10 16:28 UTC, Josh-G commented on src/Models/Company.php
> +        $this->rawDetails = $companyDetails;
add this to private properties above

2018-12-10 16:28 UTC, Josh-G commented on src/Models/Company/Director.php
> +
```suggestion
```

2018-12-10 16:28 UTC, Josh-G commented on src/Models/Company/Director.php
> +            $this->directorDetails['positions']['0']['dateAppointed'] = new \DateTime($directorDetails['positions']['0']['dateAppointed']);
we should be applying this to every director position, not just the first

2018-12-10 16:28 UTC, Josh-G commented on src/Models/Company/FinancialStatement.php
> +        var_dump($statementDetails);
this needs to come out

2018-12-10 16:28 UTC, Josh-G commented on tests/ClientTest.php
> +    public function testAuthorizationSuccess($guzzle)
i don't think we should apply strict types in test method signatures

2018-12-11 09:57 UTC, williamrenfrew approved these changes

2018-12-11 13:40 UTC, williamrenfrew approved these changes

2018-12-12 14:37 UTC, merged